import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "min-h-screen",
    "flex",
    "items-center",
    "justify-center",
    "justify-between",
    "bg-gray-50",
    "bg-white",
    "bg-blue-600",
    "bg-indigo-600",
    "text-white",
    "text-gray-900",
    "text-gray-600",
    "text-gray-500",
    "text-sm",
    "text-lg",
    "text-xl",
    "text-3xl",
    "font-bold",
    "font-semibold",
    "font-medium",
    "rounded-md",
    "rounded-lg",
    "rounded-full",
    "border",
    "border-gray-300",
    "border-gray-200",
    "shadow",
    "shadow-sm",
    "p-6",
    "p-4",
    "px-4",
    "py-2",
    "py-8",
    "mb-4",
    "mb-6",
    "mb-8",
    "mt-2",
    "mt-6",
    "ml-4",
    "space-y-4",
    "space-y-6",
    "space-y-8",
    "grid",
    "grid-cols-1",
    "gap-6",
    "w-full",
    "max-w-md",
    "max-w-7xl",
    "mx-auto",
    "hover:bg-gray-50",
    "hover:bg-indigo-700",
    "focus:outline-none",
    "focus:ring-2",
    "animate-spin",
    "h-8",
    "w-8",
    "border-b-2",
    "border-blue-600",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};

export default config;
