from __future__ import annotations

import structlog
import resend
from jinja2 import Environment, FileSystemLoader
from pathlib import Path
from typing import Any

from app.config import settings
from app.infrastructure.groq_client import GroqModel, GroqClient
from app.shared.lang_context import LangContext

logger = structlog.get_logger()


class ResendClient:
    """Async Resend email client with template support."""

    def __init__(self) -> None:
        resend.api_key = settings.RESEND_API_KEY
        self._template_env = Environment(
            loader=FileSystemLoader(
                Path(__file__).parent.parent / "contexts" / "alert_engine" / "templates"
            )
        )
        self._groq = GroqClient()

    async def send_email(
        self,
        to: str,
        subject: str,
        message: str,
        template_name: str | None = None,
        template_data: dict[str, Any] | None = None,
        trace_id: str | None = None
    ) -> str:
        """Send email via Resend."""
        try:
            # Use template if provided
            if template_name and template_data:
                html_content = self._render_template(template_name, template_data)
                # Generate AI-powered subject if not provided
                if not subject:
                    subject = await self._generate_subject(template_data)
            else:
                html_content = message

            params = {
                "from": "TenderCopilot <alerts@tendercopilot.ai>",
                "to": [to],
                "subject": subject,
                "html": html_content
            }

            response = resend.Emails.send(params)
            message_id = response.get("id")

            logger.info(
                "email_sent_via_resend",
                trace_id=trace_id,
                message_id=message_id,
                recipient=to,
                subject=subject
            )

            return message_id

        except Exception as e:
            logger.error(
                "resend_email_failed",
                trace_id=trace_id,
                recipient=to,
                subject=subject,
                error=str(e)
            )
            raise

    async def send_tender_alert(
        self,
        to: str,
        alert_data: dict[str, Any],
        trace_id: str | None = None
    ) -> str:
        """Send tender alert email using template."""
        return await self.send_email(
            to=to,
            subject="",  # Will be generated by AI
            message="",  # Will use template
            template_name="tender_alert_email.html",
            template_data=alert_data,
            trace_id=trace_id
        )

    def _render_template(self, template_name: str, data: dict[str, Any]) -> str:
        """Render Jinja2 template with data."""
        try:
            template = self._template_env.get_template(template_name)
            return template.render(**data)
        except Exception as e:
            logger.error(
                "template_render_failed",
                template_name=template_name,
                error=str(e)
            )
            raise

    async def _generate_subject(self, template_data: dict[str, Any]) -> str:
        """Generate email subject using AI."""
        try:
            prompt = f"""
            Generate a concise, professional email subject line for a tender alert.
            
            Context: {template_data}
            
            Rules:
            - Maximum 60 characters
            - Include relevant emoji if appropriate
            - Be action-oriented
            - Use title case
            - Avoid spammy language
            
            Examples:
            - "🔔 Tender Deadline: ABC Corp - 2 Days Left"
            - "🆕 New Tender: Infrastructure Project Worth $50K"
            - "📊 Bid Status Update: Submitted Successfully"
            
            Return only the subject line, nothing else.
            """

            # Use GroqClient to generate subject
            response = await self._groq.complete(
                model=GroqModel.FAST,
                system_prompt=None,
                user_prompt=prompt,
                output_schema=str,
                lang=LangContext.from_lang("en"),
                trace_id=None
            )
            
            subject = response.strip().strip('"').strip("'")
            
            # Ensure subject is not too long
            if len(subject) > 60:
                subject = subject[:57] + "..."
                
            return subject

        except Exception as e:
            logger.error(
                "ai_subject_generation_failed",
                template_data=template_data,
                error=str(e)
            )
            # Fallback subject
            return "📢 Tender Alert"
